CREATE TABLE AUTHOR (
AUTH_ID			INTEGER,
AUTHORNAME      VARCHAR(30),
AUTHORBIRTHDATE DATE,
AUTHORADDRESS   VARCHAR(100),
PRIMARY KEY (AUTH_ID)
);

CREATE TABLE BOOK (
ISBN              INTEGER,
TITLE             VARCHAR(20) NOT NULL,
SYNOPSIS          VARCHAR(100),
PRICE		      DOUBLE NOT NULL,
AUTH_ID			  INTEGER,
PRIMARY KEY (ISBN),
FOREIGN KEY (AUTH_ID) REFERENCES AUTHOR(AUTH_ID)  
);

select * FROM author;



